'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
const money=(n:number)=>new Intl.NumberFormat('en-BD',{maximumFractionDigits:0}).format(n||0);
export default function Analytics(){
 const sb=createClient(); const [tx,setTx]=useState<any[]>([]); const [cash,setCash]=useState<any[]>([]); const [opening,setOpening]=useState(0);
 useEffect(()=>{(async()=>{const [a,b,c]=await Promise.all([sb.from('transactions').select('*').order('transaction_date'),sb.from('cash_entries').select('*'),sb.from('business_settings').select('opening_capital').limit(1).single()]);setTx(a.data||[]);setCash(b.data||[]);setOpening(Number(c.data?.opening_capital||0));})();},[]);
 const buy=tx.filter(x=>x.type==='Buying'), sell=tx.filter(x=>x.type==='Selling');
 const buying=buy.reduce((s,x)=>s+Number(x.amount),0), revenue=sell.reduce((s,x)=>s+Number(x.amount),0), profit=sell.reduce((s,x)=>s+Number(x.realized_profit||0),0), expense=cash.filter(x=>x.entry_type==='Expense').reduce((s,x)=>s+Number(x.amount),0);
 const ownerBuying=buy.reduce((s,x)=>s+Number(x.owner_funded||0),0), utilization=opening?ownerBuying/opening*100:0, grossMargin=revenue?profit/revenue*100:0, net=profit-expense, netMargin=revenue?net/revenue*100:0, turnover=opening?revenue/opening:0;
 const months=useMemo(()=>{const m=new Map<string,{buy:number;sell:number;profit:number}>();tx.forEach(x=>{const k=String(x.transaction_date).slice(0,7);const v=m.get(k)||{buy:0,sell:0,profit:0};if(x.type==='Buying')v.buy+=Number(x.amount);if(x.type==='Selling'){v.sell+=Number(x.amount);v.profit+=Number(x.realized_profit||0)}m.set(k,v)});return [...m.entries()].slice(-12)},[tx]);
 const max=Math.max(1,...months.map(([,v])=>Math.max(v.buy,v.sell)));
 return <main style={{padding:32,fontFamily:'Inter,system-ui',background:'#f7f6f2',minHeight:'100vh'}}><div style={{maxWidth:1250,margin:'auto'}}><a href="/" style={{textDecoration:'none'}}>← Back to Vehicle Capital Pro</a><h1>Business Analytics</h1><p>Owner-capital performance, turnover and operating ratios. People’s Money is not treated as owner capital.</p><section style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14}}>{[['Owner Capital Utilization',utilization.toFixed(1)+'%'],['Buying Turnover','৳'+money(buying)],['Selling Turnover','৳'+money(revenue)],['Realized Selling Profit','৳'+money(profit)],['Gross Profit Margin',grossMargin.toFixed(1)+'%'],['Net Profit','৳'+money(net)],['Net Margin',netMargin.toFixed(1)+'%'],['Capital Turnover',turnover.toFixed(2)+'×']].map(([a,b])=><div key={a} style={{background:'white',padding:20,borderRadius:14,border:'1px solid #e5e3dd'}}><small>{a}</small><h2 style={{margin:'8px 0'}}>{b}</h2></div>)}</section><section style={{marginTop:20,background:'white',padding:24,borderRadius:14,border:'1px solid #e5e3dd'}}><h2>Monthly Turnover</h2>{months.length===0?<p>No transactions yet.</p>:months.map(([month,v])=><div key={month} style={{margin:'16px 0'}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{month}</b><span>Buying ৳{money(v.buy)} · Selling ৳{money(v.sell)} · Profit ৳{money(v.profit)}</span></div><div style={{height:10,background:'#eee',borderRadius:99,marginTop:6}}><div style={{height:10,width:(v.sell/max*100)+'%',background:'#173d32',borderRadius:99}}/></div></div>)}</section><section style={{marginTop:20,display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}><div style={{background:'white',padding:24,borderRadius:14}}><h2>Core Ratios</h2><p>Buying / Selling ratio: <b>{revenue? (buying/revenue).toFixed(2):'0.00'}×</b></p><p>Profit / Selling: <b>{grossMargin.toFixed(1)}%</b></p><p>Owner buying / Opening capital: <b>{utilization.toFixed(1)}%</b></p><p>Selling / Opening capital: <b>{turnover.toFixed(2)}×</b></p></div><div style={{background:'white',padding:24,borderRadius:14}}><h2>Accounting Separation</h2><p>Opening/Owner capital: <b>৳{money(opening)}</b></p><p>Owner-funded buying: <b>৳{money(ownerBuying)}</b></p><p>People’s Money remains a separate funding/liability layer.</p><p>Sales are measured as turnover; FIFO determines realized selling profit.</p></div></section></div></main>;
}
