'use client';
export default function EnterpriseSettlementTheme(){return <style jsx global>{`
  .fab{right:28px!important;bottom:28px!important;padding:9px!important;border-radius:18px!important;background:rgba(7,31,25,.96)!important;color:#fff!important;border:1px solid rgba(150,239,201,.16)!important;box-shadow:0 22px 55px rgba(2,35,27,.28)!important;backdrop-filter:blur(16px)!important}.fab>span{width:42px!important;height:42px!important;border-radius:13px!important}.fab b{font-size:11px!important}.fab small{color:#9bb9ad!important}.fab strong{color:#9de8c6!important}
  .overlay{background:rgba(1,19,14,.78)!important;backdrop-filter:blur(14px)!important;padding:16px!important}.panel{width:min(1240px,100%)!important;max-height:96vh!important;padding:30px!important;border-radius:30px!important;background:linear-gradient(145deg,#f8fcfa,#edf5f1)!important;border:1px solid #d4e4dd!important;box-shadow:0 45px 120px rgba(0,0,0,.34)!important}.panel>header{padding-bottom:18px!important;border-bottom:1px solid #dce8e3!important}.panel h2{font-size:34px!important}.panel header p{font-size:10px!important;max-width:620px!important}.summary{grid-template-columns:repeat(4,1fr)!important;gap:12px!important;margin:20px 0 14px!important}.summary>div{min-height:132px!important;padding:19px!important;border-radius:20px!important;box-shadow:0 12px 30px rgba(8,50,39,.055)!important;transition:.2s!important}.summary>div:hover{transform:translateY(-3px)!important}.summary .hero{background:linear-gradient(135deg,#052d23,#087f5b)!important}.summary b{font-size:25px!important}.capital{margin:14px 0 22px!important;padding:22px!important;border-radius:22px!important;background:linear-gradient(120deg,#071f19,#103e30)!important;position:relative!important;overflow:hidden!important}.capital:after{content:'';position:absolute;right:-80px;top:-130px;width:300px;height:300px;border:1px solid rgba(166,247,211,.12);border-radius:50%;box-shadow:0 0 0 50px rgba(166,247,211,.025)}.capital h3{font-size:32px!important}.capital button{position:relative;z-index:2!important;background:#dff8ec!important;color:#0a4b39!important;border:0!important;font-weight:800!important}
  .title{margin:24px 0 10px!important}.title b{font-size:10px!important;letter-spacing:.13em!important}.title span{font-size:8px!important;max-width:700px!important}.list{gap:8px!important}.row{min-height:61px!important;border-radius:16px!important;padding:13px 15px!important}.row:hover{transform:translateX(4px)!important}.status{letter-spacing:.02em!important}.foot{margin-top:24px!important;padding:20px!important;border:1px solid #d8e6e0!important;border-radius:20px!important;background:#fff!important;box-shadow:0 10px 25px rgba(8,50,39,.04)!important}.foot span{font-size:8px!important;line-height:1.55!important}.foot button{background:#102f26!important;border-radius:11px!important;font-weight:800!important}
  .modal-bg{background:rgba(1,19,14,.76)!important;backdrop-filter:blur(14px)!important}.modal{width:min(680px,100%)!important;border-radius:26px!important;padding:25px!important}.modal header{padding-bottom:14px!important;border-bottom:1px solid #e2ebe7!important}.form{gap:13px!important}.form label{font-weight:700!important}.form input,.form select,.form textarea{min-height:42px!important;border-radius:12px!important}.calcbox{padding:18px!important;border-radius:17px!important}.calcbox b{font-size:30px!important}
  @media(max-width:800px){.summary{grid-template-columns:1fr 1fr!important}.panel{padding:20px!important}.capital{align-items:flex-start!important;flex-direction:column!important}.foot{align-items:flex-start!important}.fab{right:15px!important;bottom:15px!important}}
  @media(max-width:520px){.summary{grid-template-columns:1fr!important}.panel{padding:15px!important;border-radius:22px!important}.panel h2{font-size:27px!important}.summary>div{min-height:105px!important}.fab div{display:none!important}.fab{padding:8px!important}}
`}</style>}
