'use client';
import SecondaryBusinessV2 from '@/components/SecondaryBusinessV2';

export default function SecondaryBusinessUI(){
  return <div className="enterprise-ui-shell"><SecondaryBusinessV2/><style jsx global>{`
    :root{--ink:#0b1713;--forest:#073b2d;--green:#087f5b;--mint:#dff7eb;--paper:#f5f8f6;--line:#dce7e2;--muted:#71827b;--gold:#b8862b;}
    html{background:var(--paper)}
    .enterprise-ui-shell{min-height:100vh;background:radial-gradient(circle at 80% 0%,rgba(55,205,150,.10),transparent 28%),linear-gradient(180deg,#f8fbf9 0%,#eef4f1 100%);color:var(--ink)}
    .enterprise-ui-shell .sb{background:transparent!important;min-height:100vh;font-family:inherit}
    .enterprise-ui-shell .sb>aside{width:270px!important;min-width:270px!important;padding:22px 16px!important;background:linear-gradient(180deg,#061f18,#092d24 55%,#061a15)!important;border-right:1px solid rgba(255,255,255,.06)!important;box-shadow:18px 0 50px rgba(5,43,34,.12);}
    .enterprise-ui-shell .brand{padding:5px 10px 28px!important;align-items:center!important;gap:12px!important}
    .enterprise-ui-shell .brand>b{width:43px!important;height:43px!important;border-radius:14px!important;background:linear-gradient(135deg,#c7f56e,#20b87f)!important;box-shadow:0 10px 30px rgba(50,220,150,.18)!important;font-size:14px!important}
    .enterprise-ui-shell .brand span{font-size:14px!important;letter-spacing:.03em!important}.enterprise-ui-shell .brand small{font-size:8px!important;letter-spacing:.14em!important;color:#78988d!important;margin-top:4px!important}
    .enterprise-ui-shell .sb>aside>button{position:relative!important;height:43px!important;border-radius:12px!important;margin:2px 0!important;padding:0 13px!important;color:#91aaa1!important;font-weight:650!important;transition:.2s!important}
    .enterprise-ui-shell .sb>aside>button:hover{background:rgba(255,255,255,.06)!important;color:#fff!important;transform:translateX(2px)}
    .enterprise-ui-shell .sb>aside>button.active{background:linear-gradient(90deg,rgba(54,216,155,.18),rgba(54,216,155,.04))!important;color:#d9fff0!important;box-shadow:inset 3px 0 #54e2ac,0 10px 25px rgba(0,0,0,.10)!important}
    .enterprise-ui-shell .rules{margin-top:auto!important;padding:14px!important;border-radius:16px!important;border:1px solid rgba(169,244,211,.10)!important;background:rgba(255,255,255,.035)!important;box-shadow:inset 0 1px rgba(255,255,255,.04)}
    .enterprise-ui-shell .rules b{color:#91e5c3!important;font-size:8px!important;letter-spacing:.16em!important}.enterprise-ui-shell .rules span{font-size:8px!important;color:#719188!important;padding-top:7px!important;line-height:1.45}
    .enterprise-ui-shell .body{background:transparent!important;padding-bottom:45px!important}
    .enterprise-ui-shell .body>header{position:sticky!important;top:0!important;z-index:20!important;padding:20px 38px!important;min-height:86px!important;background:rgba(248,251,249,.84)!important;border-bottom:1px solid rgba(214,227,221,.85)!important;backdrop-filter:blur(18px)!important}
    .enterprise-ui-shell .body>header small{font-size:8px!important;letter-spacing:.18em!important;color:#4c7567!important;font-weight:850!important}
    .enterprise-ui-shell .body>header h1{font-size:34px!important;letter-spacing:-.045em!important;margin-top:6px!important;color:#102c24!important}
    .enterprise-ui-shell .head-actions{gap:8px!important}.enterprise-ui-shell .head-actions button{border:1px solid #d4e2dc!important;background:#fff!important;border-radius:11px!important;box-shadow:0 6px 18px rgba(10,54,43,.05)!important;padding:10px 13px!important;font-weight:700!important;color:#49635a!important}.enterprise-ui-shell .head-actions .primary{background:linear-gradient(135deg,#0a8b63,#066b50)!important;color:#fff!important;border-color:#087f5b!important;box-shadow:0 10px 24px rgba(8,127,91,.20)!important}
    .enterprise-ui-shell .notice,.enterprise-ui-shell .error{margin:18px 38px 0!important;border-radius:13px!important;padding:12px 14px!important;font-size:10px!important}
    .enterprise-ui-shell .hero{position:relative!important;overflow:hidden!important;margin:28px 38px 18px!important;border-radius:26px!important;padding:34px!important;min-height:260px!important;background:radial-gradient(circle at 82% 30%,rgba(89,239,183,.20),transparent 24%),linear-gradient(120deg,#052a21,#0b5b44 70%,#087f5b)!important;box-shadow:0 28px 65px rgba(4,65,49,.20)!important}
    .enterprise-ui-shell .hero:after{content:'';position:absolute;right:-100px;bottom:-180px;width:420px;height:420px;border:1px solid rgba(196,255,228,.15);border-radius:50%;box-shadow:0 0 0 50px rgba(196,255,228,.025),0 0 0 100px rgba(196,255,228,.018)}
    .enterprise-ui-shell .hero>div{position:relative;z-index:2}.enterprise-ui-shell .hero span{font-size:8px!important;letter-spacing:.18em!important;color:#9debc9!important}.enterprise-ui-shell .hero h2{font-size:42px!important;line-height:1.02!important;letter-spacing:-.055em!important;margin:12px 0!important}.enterprise-ui-shell .hero p{max-width:580px!important;font-size:11px!important;color:#c1ddd2!important;line-height:1.7!important}
    .enterprise-ui-shell .master-quick{border:1px solid rgba(255,255,255,.16)!important;background:rgba(255,255,255,.09)!important;backdrop-filter:blur(16px)!important;border-radius:18px!important;padding:18px!important;box-shadow:0 18px 40px rgba(0,0,0,.12)!important}.enterprise-ui-shell .master-quick b{color:#fff!important;letter-spacing:.1em!important}.enterprise-ui-shell .master-quick small{color:#a9d1c1!important}
    .enterprise-ui-shell .section-title{margin:28px 38px 11px!important;font-size:9px!important;letter-spacing:.16em!important;font-weight:900!important;color:#28483e!important;display:flex!important;align-items:center!important;gap:12px}.enterprise-ui-shell .section-title:after{content:'';height:1px;background:#d9e5e0;flex:1}
    .enterprise-ui-shell .cards{padding:0 38px!important;gap:12px!important;grid-template-columns:repeat(auto-fit,minmax(190px,1fr))!important}
    .enterprise-ui-shell .cards>.card{position:relative!important;overflow:hidden!important;min-height:125px!important;padding:18px!important;border-radius:18px!important;border:1px solid #dce7e2!important;background:rgba(255,255,255,.92)!important;box-shadow:0 10px 30px rgba(9,56,44,.055)!important;transition:.2s!important}.enterprise-ui-shell .cards>.card:hover{transform:translateY(-4px)!important;box-shadow:0 18px 35px rgba(9,56,44,.10)!important;border-color:#b9ddce!important}.enterprise-ui-shell .cards>.card:before{content:'';position:absolute;right:-30px;top:-35px;width:95px;height:95px;border-radius:50%;background:rgba(8,127,91,.055)}
    .enterprise-ui-shell .cards>.card b{font-size:23px!important;letter-spacing:-.035em!important;color:#123a2e!important}.enterprise-ui-shell .cards>.card span{font-size:7px!important;letter-spacing:.1em!important;color:#7d9088!important;text-transform:uppercase!important}
    .enterprise-ui-shell .panel{margin:18px 38px!important;border:1px solid #dce7e2!important;border-radius:21px!important;background:rgba(255,255,255,.86)!important;box-shadow:0 15px 40px rgba(8,55,43,.06)!important;padding:20px!important}
    .enterprise-ui-shell .projection{padding:22px!important}.enterprise-ui-shell .projection>b{font-size:12px!important;letter-spacing:.04em!important}.enterprise-ui-shell .seg{margin:12px 0!important;background:#edf3f0!important;padding:4px!important;border-radius:12px!important}.enterprise-ui-shell .seg button{border:0!important;background:transparent!important;border-radius:9px!important;padding:8px 12px!important;color:#71847c!important;font-weight:700!important}.enterprise-ui-shell .seg button.sel{background:#fff!important;color:#087f5b!important;box-shadow:0 4px 12px rgba(8,55,43,.08)!important}
    .enterprise-ui-shell .list{margin:0 38px!important;gap:8px!important}.enterprise-ui-shell .list .row{border:1px solid #dce7e2!important;border-radius:15px!important;background:rgba(255,255,255,.94)!important;padding:14px 15px!important;box-shadow:0 5px 18px rgba(8,55,43,.035)!important;transition:.18s!important}.enterprise-ui-shell .list .row:hover{transform:translateY(-2px)!important;border-color:#a8d7c5!important;box-shadow:0 12px 25px rgba(8,127,91,.08)!important}.enterprise-ui-shell .list .row b{font-size:10px!important;color:#173b31!important}.enterprise-ui-shell .list .row small{font-size:7px!important;color:#7d8f88!important}.enterprise-ui-shell .status{font-size:7px!important;padding:7px 9px!important;font-weight:850!important}.enterprise-ui-shell .edit-pill{font-size:7px!important;border-radius:8px!important}
    .enterprise-ui-shell .sb-loading{min-height:100vh!important;display:grid!important;place-items:center!important;background:#f4f8f6!important;color:#31564a!important;font-weight:700!important}
    .enterprise-ui-shell .modal-bg{z-index:2000!important;background:rgba(2,25,19,.70)!important;backdrop-filter:blur(12px)!important}.enterprise-ui-shell .modal{border-radius:24px!important;border:1px solid #dce9e3!important;box-shadow:0 40px 110px rgba(0,0,0,.30)!important;padding:23px!important}.enterprise-ui-shell .modal h3{font-size:23px!important;letter-spacing:-.035em!important}.enterprise-ui-shell .form input,.enterprise-ui-shell .form select,.enterprise-ui-shell .form textarea{border-radius:11px!important;border-color:#d6e4de!important;padding:11px!important;box-shadow:inset 0 1px 2px rgba(8,55,43,.025)!important}.enterprise-ui-shell .form input:focus,.enterprise-ui-shell .form select:focus,.enterprise-ui-shell .form textarea:focus{outline:2px solid rgba(8,127,91,.12)!important;border-color:#73c5a5!important}.enterprise-ui-shell .calcbox{border-radius:16px!important;background:linear-gradient(135deg,#effaf5,#fff)!important;border-color:#bfe2d2!important;box-shadow:0 10px 25px rgba(8,127,91,.06)!important}.enterprise-ui-shell .calcbox b{font-size:27px!important}.enterprise-ui-shell .save{background:linear-gradient(135deg,#0a8b63,#066b50)!important;box-shadow:0 10px 22px rgba(8,127,91,.18)!important}
    @media(max-width:900px){.enterprise-ui-shell .sb>aside{width:230px!important;min-width:230px!important}.enterprise-ui-shell .body>header{padding:17px 22px!important}.enterprise-ui-shell .hero,.enterprise-ui-shell .section-title{margin-left:22px!important;margin-right:22px!important}.enterprise-ui-shell .cards,.enterprise-ui-shell .list{padding-left:22px!important;padding-right:22px!important;margin-left:0!important;margin-right:0!important}.enterprise-ui-shell .panel{margin-left:22px!important;margin-right:22px!important}}
    @media(max-width:700px){.enterprise-ui-shell .sb>aside{width:100%!important;min-width:0!important;position:relative!important;min-height:auto!important}.enterprise-ui-shell .sb{display:block!important}.enterprise-ui-shell .sb>aside{padding:14px!important}.enterprise-ui-shell .rules{display:none!important}.enterprise-ui-shell .sb>aside>button{display:inline-flex!important;width:calc(50% - 5px)!important;margin:2px!important}.enterprise-ui-shell .brand{padding-bottom:14px!important}.enterprise-ui-shell .body>header{position:relative!important;padding:16px!important}.enterprise-ui-shell .hero{margin:16px!important;padding:24px!important}.enterprise-ui-shell .hero h2{font-size:32px!important}.enterprise-ui-shell .section-title{margin:22px 16px 10px!important}.enterprise-ui-shell .cards{padding:0 16px!important;grid-template-columns:1fr 1fr!important}.enterprise-ui-shell .list{padding:0 16px!important}.enterprise-ui-shell .panel{margin:14px 16px!important}.enterprise-ui-shell .head-actions .primary{padding:9px!important}.enterprise-ui-shell .head-actions button:first-child{display:none!important}}
    @media(max-width:480px){.enterprise-ui-shell .cards{grid-template-columns:1fr!important}.enterprise-ui-shell .body>header h1{font-size:27px!important}.enterprise-ui-shell .body>header{align-items:flex-end!important}.enterprise-ui-shell .head-actions{max-width:130px}.enterprise-ui-shell .head-actions .primary{white-space:nowrap;font-size:9px!important}}
  `}</style></div>;
}
