'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

const money=(n:number)=>new Intl.NumberFormat('en-BD',{maximumFractionDigits:2}).format(Number(n)||0);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Dhaka'});
type Tx={id:string;type:string;party_id:string;transaction_date:string;due_date:string|null;units:number;rate:number;amount:number;paid:number;return_paid:number;people_funded:number;owner_funded:number;note:string|null;basis:string;start_date:string;end_date:string|null;realized_profit:number};
type Party={id:string;name:string};

export default function Transactions(){
 const supabase=createClient();
 const [rows,setRows]=useState<Tx[]>([]); const [parties,setParties]=useState<Party[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [editing,setEditing]=useState<Tx|null>(null); const [renewing,setRenewing]=useState<Tx|null>(null); const [viewing,setViewing]=useState<Tx|null>(null); const [saving,setSaving]=useState(false);
 const [type,setType]=useState('All'); const [party,setParty]=useState('All'); const [query,setQuery]=useState(''); const [status,setStatus]=useState('All');
 const load=async()=>{setError('');const [t,p]=await Promise.all([supabase.from('transactions').select('*').order('transaction_date',{ascending:false}),supabase.from('parties').select('id,name').order('name')]);if(t.error||p.error)setError(t.error?.message||p.error?.message||'Unable to load transactions.');setRows((t.data||[]) as Tx[]);setParties((p.data||[]) as Party[]);setLoading(false)};
 useEffect(()=>{load();const c=supabase.channel('transaction-management').on('postgres_changes',{event:'*',schema:'public',table:'transactions'},load).on('postgres_changes',{event:'*',schema:'public',table:'parties'},load).subscribe();return()=>{supabase.removeChannel(c)}},[]);
 const name=(id:string)=>parties.find(p=>p.id===id)?.name||id.slice(0,8)+'…';
 const filtered=useMemo(()=>rows.filter(x=>{const s=x.paid>=x.amount?'Paid':x.paid>0?'Partially Paid':x.due_date&&x.due_date<today()?'Overdue':'Pending';return(type==='All'||x.type===type)&&(party==='All'||x.party_id===party)&&(status==='All'||s===status)&&(!query||name(x.party_id).toLowerCase().includes(query.toLowerCase())||x.id.toLowerCase().includes(query.toLowerCase()))}),[rows,parties,type,party,status,query]);
 const edit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;setSaving(true);setError('');const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('update_financial_transaction',{p_transaction_id:editing.id,p_transaction_date:String(f.get('date')),p_due_date:String(f.get('due')||'')||null,p_rate:Number(f.get('rate'))||0,p_basis:String(f.get('basis')),p_start_date:String(f.get('start')),p_end_date:String(f.get('end')||'')||null,p_note:String(f.get('note')||'')});if(error)setError(error.message);else{setEditing(null);await load()}setSaving(false)};
 const renew=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!renewing)return;setSaving(true);setError('');const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('renew_financial_transaction',{p_transaction_id:renewing.id,p_due_date:String(f.get('due')||'')||null,p_end_date:String(f.get('end')||'')||null,p_rate:Number(f.get('rate'))||renewing.rate,p_note:String(f.get('note')||'')||null});if(error)setError(error.message);else{setRenewing(null);await load()}setSaving(false)};
 const exportCsv=()=>{const data=[['Date','Type','Party','Units','Amount','Paid','Rate','Basis','Due','Status','Realized Profit'],...filtered.map(x=>[x.transaction_date,x.type,name(x.party_id),x.units,x.amount,x.paid,x.rate,x.basis,x.due_date||'',x.paid>=x.amount?'Paid':x.paid>0?'Partially Paid':x.due_date&&x.due_date<today()?'Overdue':'Pending',x.realized_profit])];const csv=data.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`A-P-Traders-Transactions-${today()}.csv`;a.click()};
 if(loading)return <main style={{padding:32,fontFamily:'Inter,system-ui'}}>Loading transactions…</main>;
 return <main style={{minHeight:'100vh',background:'#f5f7f3',padding:'30px 34px',fontFamily:'Inter,system-ui',color:'#101713'}}><div style={{maxWidth:1500,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-end',marginBottom:22}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#166534'}}>A P TRADERS · SECOND BUSINESS</div><h1 style={{margin:'6px 0',fontSize:34}}>Transaction Management</h1><p style={{margin:0,color:'#68726c'}}>One controlled place to view, edit and renew transactions through the financial engine.</p></div><div style={{display:'flex',gap:8}}><button onClick={exportCsv} style={btn}>Export CSV</button><Link href="/secondary" style={{...btn,textDecoration:'none'}}>← Dashboard</Link></div></header>
 {error&&<div style={{padding:12,marginBottom:16,background:'#fff1f2',color:'#b42318',borderRadius:10}}>{error}</div>}
 <section style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:10,marginBottom:14}}><input placeholder="Search party or transaction ID" value={query} onChange={e=>setQuery(e.target.value)} style={input}/><select value={type} onChange={e=>setType(e.target.value)} style={input}><option>All</option><option>Buying</option><option>Selling</option></select><select value={party} onChange={e=>setParty(e.target.value)} style={input}><option value="All">All Parties</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} style={input}><option>All</option><option>Paid</option><option>Partially Paid</option><option>Overdue</option><option>Pending</option></select></section>
 <section style={{background:'#fff',border:'1px solid #e1e6e1',borderRadius:16,overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Date','Type','Party','Units','Amount','Paid','Rate','Basis','Due','Status','Profit','Actions'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(x=>{const st=x.paid>=x.amount?'Paid':x.paid>0?'Partially Paid':x.due_date&&x.due_date<today()?'Overdue':'Pending';return <tr key={x.id}><td style={td}>{x.transaction_date}</td><td style={td}><span style={{fontWeight:700}}>{x.type}</span></td><td style={td}>{name(x.party_id)}</td><td style={td}>{x.units}</td><td style={td}>৳{money(x.amount)}</td><td style={td}>৳{money(x.paid)}</td><td style={td}>{x.rate}</td><td style={td}>{x.basis}</td><td style={td}>{x.due_date||'—'}</td><td style={td}>{st}</td><td style={td}>৳{money(x.realized_profit)}</td><td style={{...td,whiteSpace:'nowrap'}}><button onClick={()=>setViewing(x)} style={small}>View</button><button onClick={()=>setEditing(x)} disabled={x.paid>0} style={small}>Edit</button>{x.type==='Buying'&&<button onClick={()=>setRenewing(x)} disabled={x.paid<x.amount} style={small}>Renew</button>}</td></tr>})}</tbody></table>{!filtered.length&&<div style={{padding:30,textAlign:'center',color:'#68726c'}}>No transactions match these filters.</div>}</section>
 <div style={{fontSize:11,color:'#68726c',marginTop:10}}>{filtered.length} transaction(s) · Live · Asia/Dhaka · Edit is locked after principal payment.</div>
 </div>
 {viewing&&<Modal title="Transaction Details" onClose={()=>setViewing(null)}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,fontSize:13}}>{[['Transaction ID',viewing.id],['Type',viewing.type],['Party',name(viewing.party_id)],['Date',viewing.transaction_date],['Due Date',viewing.due_date||'—'],['Units',viewing.units],['Amount','৳'+money(viewing.amount)],['Paid','৳'+money(viewing.paid)],['Investor Return Paid','৳'+money(viewing.return_paid)],['People Funded','৳'+money(viewing.people_funded)],['Owner Funded','৳'+money(viewing.owner_funded)],['Rate',viewing.rate],['Basis',viewing.basis],['Start Date',viewing.start_date],['End Date',viewing.end_date||'—'],['Realized Profit','৳'+money(viewing.realized_profit)]].map(([k,v])=><div key={String(k)}><div style={{fontSize:10,color:'#68726c',textTransform:'uppercase'}}>{k}</div><strong>{String(v)}</strong></div>)}</div>{viewing.note&&<p style={{marginTop:18,padding:12,background:'#f5f7f3',borderRadius:9}}>{viewing.note}</p>}</Modal>}
 {editing&&<Modal title="Edit Transaction" onClose={()=>setEditing(null)}><form onSubmit={edit} style={form}><Field label="Transaction Date" name="date" type="date" defaultValue={editing.transaction_date}/><Field label="Due Date" name="due" type="date" defaultValue={editing.due_date||''}/><Field label="Rate" name="rate" type="number" step="0.01" defaultValue={editing.rate}/><label>Basis<select name="basis" defaultValue={editing.basis} style={input}><option>Monthly</option><option>Daily</option></select></label><Field label="Start Date" name="start" type="date" defaultValue={editing.start_date}/><Field label="End Date" name="end" type="date" defaultValue={editing.end_date||''}/><Field label="Note" name="note" defaultValue={editing.note||''}/><div style={{gridColumn:'1/-1',textAlign:'right'}}><button type="button" onClick={()=>setEditing(null)} style={btn}>Cancel</button> <button disabled={saving} style={primary}>{saving?'Saving…':'Save Changes'}</button></div></form></Modal>}
 {renewing&&<Modal title="Renew Buying" onClose={()=>setRenewing(null)}><form onSubmit={renew} style={form}><Field label="New Due Date" name="due" type="date"/><Field label="New End Date" name="end" type="date"/><Field label="Rate" name="rate" type="number" step="0.01" defaultValue={renewing.rate}/><Field label="Note" name="note" defaultValue="Renewal"/><div style={{gridColumn:'1/-1',textAlign:'right'}}><button type="button" onClick={()=>setRenewing(null)} style={btn}>Cancel</button> <button disabled={saving} style={primary}>{saving?'Saving…':'Create Renewal'}</button></div></form></Modal>}
 </main>;
}
function Field({label,name,type='text',defaultValue='' }:{label:string;name:string;type?:string;defaultValue?:string|number}){return <label style={{fontSize:12}}>{label}<input name={name} type={type} defaultValue={defaultValue} required={name!=='note'} style={input}/></label>}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div style={{position:'fixed',inset:0,zIndex:20,background:'rgba(16,23,19,.45)',display:'grid',placeItems:'center',padding:20}}><div style={{background:'#fff',borderRadius:16,padding:22,width:'min(820px,100%)',maxHeight:'90vh',overflow:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><h2 style={{margin:0}}>{title}</h2><button onClick={onClose} style={btn}>Close</button></div>{children}</div></div>}
const input={width:'100%',boxSizing:'border-box' as const,padding:'10px 11px',border:'1px solid #d7ddd8',borderRadius:9,background:'#fff',marginTop:5};
const btn={padding:'9px 12px',border:'1px solid #d7ddd8',borderRadius:9,background:'#fff',color:'#101713',cursor:'pointer'};
const primary={...btn,background:'#14532d',color:'#fff',borderColor:'#14532d'};
const small={...btn,padding:'6px 8px',marginRight:5,fontSize:11};
const th={textAlign:'left' as const,padding:12,background:'#f7f8f5',whiteSpace:'nowrap'};
const td={padding:12,borderTop:'1px solid #edf0ed',whiteSpace:'nowrap' as const};
const form={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14};
